# Create a configmap
apiVersion: v1
kind: ConfigMap
metadata:
  name: apl-fila-config
  labels:
    app: apl-fila
data:
  DATASOURCE_INITIALIZATION_MODE: always
  DATASOURCE_INITIALIZE: 'true'
  DATASOURCE_CONTINUE_ON_ERROR: 'true'
  HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
  HIBERNATE_SHOW_SQL: 'true'
  HIBERNATE_DDL_AUTO: update
  SERVER_PORT: '9092'
  SERVLET_CONTEXT_PATH: /tech-challenge
  FEIGN_CONNECT_TIMEOUT: '14000'
  FEIGN_READ_TIMEOUT: '14000'
  QUEUE_FILA_PEDIDO: 'Fila1'
  QUEUE_UPDATE_PEDIDO: 'StatusChange'